# Usa una imagen base ligera de Python 3.10
FROM python:3.10-slim

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia todo el contenido del proyecto al contenedor
COPY . .

# Instala las dependencias definidas en requirements.txt sin usar caché
RUN pip install --no-cache-dir -r requirements.txt

# Comando que ejecuta la aplicación usando uvicorn como servidor ASGI
ENV PORT=8000
CMD ["python", "-m", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]